# Generated by Django 4.2.7 on 2024-01-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrade1Year',
            fields=[
                ('symbol', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('last_refreshed', models.DateField()),
                ('date_trade', models.DateField()),
                ('open_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'daily_trade_1year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyTradeLast',
            fields=[
                ('symbol', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('last_refreshed', models.DateField()),
                ('date_trade', models.DateField()),
                ('open_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'last_daily_trade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('symbol', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fiscal_date_ending', models.DateField()),
                ('reported_currency', models.CharField(max_length=3)),
                ('total_revenue', models.BigIntegerField()),
                ('cost_of_goods_and_services_sold', models.BigIntegerField()),
                ('operating_income', models.BigIntegerField()),
                ('depreciation_and_amortization', models.BigIntegerField()),
                ('income_tax_expense', models.BigIntegerField()),
                ('interest_and_debt_expense', models.BigIntegerField()),
                ('netincome', models.BigIntegerField()),
                ('ebit', models.BigIntegerField()),
                ('ebitda', models.BigIntegerField()),
            ],
            options={
                'db_table': 'light_income_statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis1Year',
            fields=[
                ('symbol', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('max_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('min_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_highlow_perc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('max_volume', models.BigIntegerField()),
                ('min_volume', models.BigIntegerField()),
                ('average_volume', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_volume_perc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('average_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('standard_deviation', models.DecimalField(decimal_places=4, max_digits=10)),
                ('standard_deviation_over_mean', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'stock_analysis_1year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TradeVar',
            fields=[
                ('symbol', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('date_trade', models.DateField()),
                ('close_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_trade_1day', models.DateField()),
                ('close_value_1day', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_1day', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_1day_perc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_trade_1month', models.DateField()),
                ('close_value_1month', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_1month', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_1month_perc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_trade_3months', models.DateField()),
                ('close_value_3months', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_3months', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_3months_perc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_trade_6months', models.DateField()),
                ('close_value_6months', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_6months', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_6months_perc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_trade_1year', models.DateField()),
                ('close_value_1year', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_1year', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_1year_perc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_trade_5years', models.DateField()),
                ('close_value_5years', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_5years', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_5years_perc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_trade_10years', models.DateField()),
                ('close_value_10years', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_10years', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_10years_perc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_trade_20years', models.DateField()),
                ('close_value_20years', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_20years', models.DecimalField(decimal_places=4, max_digits=10)),
                ('var_20years_perc', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'daily_trade_var',
                'managed': False,
            },
        ),
    ]
